# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56ce959a391093f539d36e14df8ba2ce31ddc84575b9b6ec45e8ab14de913ea8aedc04719ac501e9cb6cf45bbd9560180d05b7eb52b38cbc7b35e4d4c8fd553d

test:
  secret_key_base: d20773e93c11a3dcdfb4171a0841485d5b36129078a437dfe0edc536e7ef2e8819bdad8e1204973fc018b7f7572df5ff74e7b99bcdc4e82cb5020589b186e324

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
